/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Currency} from './Currency';

/**
 * The BankAccount model module.
 * @module model/BankAccount
 * @version 3.0.14
 */
export class BankAccount {
  /**
   * Constructs a new <code>BankAccount</code>.
   * @alias module:model/BankAccount
   * @class
   * @param name {String} 
   * @param accountNumber {String} 
   * @param currency {module:model/Currency} 
   */
  constructor(name, accountNumber, currency) {
    this.name = name;
    this.accountNumber = accountNumber;
    this.currency = currency;
  }

  /**
   * Constructs a <code>BankAccount</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BankAccount} obj Optional instance to populate.
   * @return {module:model/BankAccount} The populated <code>BankAccount</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BankAccount();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('account_number'))
        obj.accountNumber = ApiClient.convertToType(data['account_number'], 'String');
      if (data.hasOwnProperty('account_number_iban'))
        obj.accountNumberIban = ApiClient.convertToType(data['account_number_iban'], 'String');
      if (data.hasOwnProperty('swift'))
        obj.swift = ApiClient.convertToType(data['swift'], 'String');
      if (data.hasOwnProperty('currency'))
        obj.currency = Currency.constructFromObject(data['currency']);
      if (data.hasOwnProperty('need_qr'))
        obj.needQr = ApiClient.convertToType(data['need_qr'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
BankAccount.prototype.id = undefined;

/**
 * @member {String} name
 */
BankAccount.prototype.name = undefined;

/**
 * @member {String} accountNumber
 */
BankAccount.prototype.accountNumber = undefined;

/**
 * @member {String} accountNumberIban
 */
BankAccount.prototype.accountNumberIban = undefined;

/**
 * @member {String} swift
 */
BankAccount.prototype.swift = undefined;

/**
 * @member {module:model/Currency} currency
 */
BankAccount.prototype.currency = undefined;

/**
 * @member {Boolean} needQr
 * @default false
 */
BankAccount.prototype.needQr = false;

