/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class CheckTaxNumberMessage.
 * @enum {String}
 * @readonly
 */
const CheckTaxNumberMessage = {
  /**
   * value: "external_nav_service_unreachable"
   * @const
   */
  externalNavServiceUnreachable: "external_nav_service_unreachable",

  /**
   * value: "invalid_tax_number"
   * @const
   */
  invalidTaxNumber: "invalid_tax_number",

  /**
   * value: "no_online_szamla_settings"
   * @const
   */
  noOnlineSzamlaSettings: "no_online_szamla_settings",

  /**
   * value: "non_exist_tax_number"
   * @const
   */
  nonExistTaxNumber: "non_exist_tax_number",

  /**
   * value: "validation_ok"
   * @const
   */
  validationOk: "validation_ok",

  /**
   * Returns a <code>CheckTaxNumberMessage</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/CheckTaxNumberMessage} The enum <code>CheckTaxNumberMessage</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {CheckTaxNumberMessage};