/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DocumentVatRateSummary model module.
 * @module model/DocumentVatRateSummary
 * @version 3.0.14
 */
export class DocumentVatRateSummary {
  /**
   * Constructs a new <code>DocumentVatRateSummary</code>.
   * @alias module:model/DocumentVatRateSummary
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentVatRateSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentVatRateSummary} obj Optional instance to populate.
   * @return {module:model/DocumentVatRateSummary} The populated <code>DocumentVatRateSummary</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentVatRateSummary();
      if (data.hasOwnProperty('vat_name'))
        obj.vatName = ApiClient.convertToType(data['vat_name'], 'String');
      if (data.hasOwnProperty('vat_percentage'))
        obj.vatPercentage = ApiClient.convertToType(data['vat_percentage'], 'Number');
      if (data.hasOwnProperty('vat_rate_net_amount'))
        obj.vatRateNetAmount = ApiClient.convertToType(data['vat_rate_net_amount'], 'Number');
      if (data.hasOwnProperty('vat_rate_vat_amount'))
        obj.vatRateVatAmount = ApiClient.convertToType(data['vat_rate_vat_amount'], 'Number');
      if (data.hasOwnProperty('vat_rate_vat_amount_local'))
        obj.vatRateVatAmountLocal = ApiClient.convertToType(data['vat_rate_vat_amount_local'], 'Number');
      if (data.hasOwnProperty('vat_rate_gross_amount'))
        obj.vatRateGrossAmount = ApiClient.convertToType(data['vat_rate_gross_amount'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} vatName
 */
DocumentVatRateSummary.prototype.vatName = undefined;

/**
 * @member {Number} vatPercentage
 */
DocumentVatRateSummary.prototype.vatPercentage = undefined;

/**
 * @member {Number} vatRateNetAmount
 */
DocumentVatRateSummary.prototype.vatRateNetAmount = undefined;

/**
 * @member {Number} vatRateVatAmount
 */
DocumentVatRateSummary.prototype.vatRateVatAmount = undefined;

/**
 * @member {Number} vatRateVatAmountLocal
 */
DocumentVatRateSummary.prototype.vatRateVatAmountLocal = undefined;

/**
 * @member {Number} vatRateGrossAmount
 */
DocumentVatRateSummary.prototype.vatRateGrossAmount = undefined;

