/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DocumentBlockType} from './DocumentBlockType';

/**
 * The DocumentBlock model module.
 * @module model/DocumentBlock
 * @version 3.0.14
 */
export class DocumentBlock {
  /**
   * Constructs a new <code>DocumentBlock</code>.
   * @alias module:model/DocumentBlock
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentBlock</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentBlock} obj Optional instance to populate.
   * @return {module:model/DocumentBlock} The populated <code>DocumentBlock</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentBlock();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('prefix'))
        obj.prefix = ApiClient.convertToType(data['prefix'], 'String');
      if (data.hasOwnProperty('custom_field1'))
        obj.customField1 = ApiClient.convertToType(data['custom_field1'], 'String');
      if (data.hasOwnProperty('custom_field2'))
        obj.customField2 = ApiClient.convertToType(data['custom_field2'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = DocumentBlockType.constructFromObject(data['type']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
DocumentBlock.prototype.id = undefined;

/**
 * @member {String} name
 */
DocumentBlock.prototype.name = undefined;

/**
 * @member {String} prefix
 */
DocumentBlock.prototype.prefix = undefined;

/**
 * @member {String} customField1
 */
DocumentBlock.prototype.customField1 = undefined;

/**
 * @member {String} customField2
 */
DocumentBlock.prototype.customField2 = undefined;

/**
 * @member {module:model/DocumentBlockType} type
 */
DocumentBlock.prototype.type = undefined;

