/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Address} from './Address';
import {PartnerTaxType} from './PartnerTaxType';

/**
 * The DocumentPartner model module.
 * @module model/DocumentPartner
 * @version 3.0.14
 */
export class DocumentPartner {
  /**
   * Constructs a new <code>DocumentPartner</code>.
   * @alias module:model/DocumentPartner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentPartner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentPartner} obj Optional instance to populate.
   * @return {module:model/DocumentPartner} The populated <code>DocumentPartner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentPartner();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = Address.constructFromObject(data['address']);
      if (data.hasOwnProperty('emails'))
        obj.emails = ApiClient.convertToType(data['emails'], ['String']);
      if (data.hasOwnProperty('taxcode'))
        obj.taxcode = ApiClient.convertToType(data['taxcode'], 'String');
      if (data.hasOwnProperty('iban'))
        obj.iban = ApiClient.convertToType(data['iban'], 'String');
      if (data.hasOwnProperty('swift'))
        obj.swift = ApiClient.convertToType(data['swift'], 'String');
      if (data.hasOwnProperty('account_number'))
        obj.accountNumber = ApiClient.convertToType(data['account_number'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('tax_type'))
        obj.taxType = PartnerTaxType.constructFromObject(data['tax_type']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
DocumentPartner.prototype.id = undefined;

/**
 * @member {String} name
 */
DocumentPartner.prototype.name = undefined;

/**
 * @member {module:model/Address} address
 */
DocumentPartner.prototype.address = undefined;

/**
 * @member {Array.<String>} emails
 */
DocumentPartner.prototype.emails = undefined;

/**
 * @member {String} taxcode
 */
DocumentPartner.prototype.taxcode = undefined;

/**
 * @member {String} iban
 */
DocumentPartner.prototype.iban = undefined;

/**
 * @member {String} swift
 */
DocumentPartner.prototype.swift = undefined;

/**
 * @member {String} accountNumber
 */
DocumentPartner.prototype.accountNumber = undefined;

/**
 * @member {String} phone
 */
DocumentPartner.prototype.phone = undefined;

/**
 * @member {module:model/PartnerTaxType} taxType
 */
DocumentPartner.prototype.taxType = undefined;

