/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class DocumentExportSortBy.
 * @enum {String}
 * @readonly
 */
const DocumentExportSortBy = {
  /**
   * value: "fulfillment_date"
   * @const
   */
  fulfillmentDate: "fulfillment_date",

  /**
   * value: "invoice_date"
   * @const
   */
  invoiceDate: "invoice_date",

  /**
   * value: "invoice_raw_number"
   * @const
   */
  invoiceRawNumber: "invoice_raw_number",

  /**
   * Returns a <code>DocumentExportSortBy</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/DocumentExportSortBy} The enum <code>DocumentExportSortBy</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {DocumentExportSortBy};