/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {LedgerNumberInformation} from './LedgerNumberInformation';

/**
 * The DocumentExportFilterExtra model module.
 * @module model/DocumentExportFilterExtra
 * @version 3.0.14
 */
export class DocumentExportFilterExtra {
  /**
   * Constructs a new <code>DocumentExportFilterExtra</code>.
   * @alias module:model/DocumentExportFilterExtra
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentExportFilterExtra</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentExportFilterExtra} obj Optional instance to populate.
   * @return {module:model/DocumentExportFilterExtra} The populated <code>DocumentExportFilterExtra</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentExportFilterExtra();
      if (data.hasOwnProperty('tensoft_vkod'))
        obj.tensoftVkod = ApiClient.convertToType(data['tensoft_vkod'], 'String');
      if (data.hasOwnProperty('ledger_number'))
        obj.ledgerNumber = LedgerNumberInformation.constructFromObject(data['ledger_number']);
      if (data.hasOwnProperty('forintsoft_konyvelesi_naplo_szam'))
        obj.forintsoftKonyvelesiNaploSzam = ApiClient.convertToType(data['forintsoft_konyvelesi_naplo_szam'], 'String');
      if (data.hasOwnProperty('positive_ledger_number'))
        obj.positiveLedgerNumber = ApiClient.convertToType(data['positive_ledger_number'], 'String');
      if (data.hasOwnProperty('negative_ledger_number'))
        obj.negativeLedgerNumber = ApiClient.convertToType(data['negative_ledger_number'], 'String');
      if (data.hasOwnProperty('rlb_kata'))
        obj.rlbKata = ApiClient.convertToType(data['rlb_kata'], 'Boolean');
      if (data.hasOwnProperty('rlb_note'))
        obj.rlbNote = ApiClient.convertToType(data['rlb_note'], 'String');
      if (data.hasOwnProperty('novitax_naplokod'))
        obj.novitaxNaplokod = ApiClient.convertToType(data['novitax_naplokod'], 'String');
      if (data.hasOwnProperty('use_gross_values'))
        obj.useGrossValues = ApiClient.convertToType(data['use_gross_values'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} tensoftVkod
 */
DocumentExportFilterExtra.prototype.tensoftVkod = undefined;

/**
 * @member {module:model/LedgerNumberInformation} ledgerNumber
 */
DocumentExportFilterExtra.prototype.ledgerNumber = undefined;

/**
 * @member {String} forintsoftKonyvelesiNaploSzam
 */
DocumentExportFilterExtra.prototype.forintsoftKonyvelesiNaploSzam = undefined;

/**
 * @member {String} positiveLedgerNumber
 */
DocumentExportFilterExtra.prototype.positiveLedgerNumber = undefined;

/**
 * @member {String} negativeLedgerNumber
 */
DocumentExportFilterExtra.prototype.negativeLedgerNumber = undefined;

/**
 * @member {Boolean} rlbKata
 */
DocumentExportFilterExtra.prototype.rlbKata = undefined;

/**
 * @member {String} rlbNote
 */
DocumentExportFilterExtra.prototype.rlbNote = undefined;

/**
 * @member {String} novitaxNaplokod
 */
DocumentExportFilterExtra.prototype.novitaxNaplokod = undefined;

/**
 * @member {Boolean} useGrossValues
 */
DocumentExportFilterExtra.prototype.useGrossValues = undefined;

