/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DocumentType} from './DocumentType';
import {OnlinePayment} from './OnlinePayment';
import {Round} from './Round';

/**
 * The DocumentSettings model module.
 * @module model/DocumentSettings
 * @version 3.0.14
 */
export class DocumentSettings {
  /**
   * Constructs a new <code>DocumentSettings</code>.
   * @alias module:model/DocumentSettings
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentSettings} obj Optional instance to populate.
   * @return {module:model/DocumentSettings} The populated <code>DocumentSettings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentSettings();
      if (data.hasOwnProperty('mediated_service'))
        obj.mediatedService = ApiClient.convertToType(data['mediated_service'], 'Boolean');
      if (data.hasOwnProperty('without_financial_fulfillment'))
        obj.withoutFinancialFulfillment = ApiClient.convertToType(data['without_financial_fulfillment'], 'Boolean');
      if (data.hasOwnProperty('online_payment'))
        obj.onlinePayment = OnlinePayment.constructFromObject(data['online_payment']);
      if (data.hasOwnProperty('round'))
        obj.round = Round.constructFromObject(data['round']);
      if (data.hasOwnProperty('no_send_onlineszamla_by_user'))
        obj.noSendOnlineszamlaByUser = ApiClient.convertToType(data['no_send_onlineszamla_by_user'], 'Boolean');
      if (data.hasOwnProperty('order_number'))
        obj.orderNumber = ApiClient.convertToType(data['order_number'], 'String');
      if (data.hasOwnProperty('place_id'))
        obj.placeId = ApiClient.convertToType(data['place_id'], 'Number');
      if (data.hasOwnProperty('instant_payment'))
        obj.instantPayment = ApiClient.convertToType(data['instant_payment'], 'Boolean');
      if (data.hasOwnProperty('selected_type'))
        obj.selectedType = DocumentType.constructFromObject(data['selected_type']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} mediatedService
 * @default false
 */
DocumentSettings.prototype.mediatedService = false;

/**
 * @member {Boolean} withoutFinancialFulfillment
 * @default false
 */
DocumentSettings.prototype.withoutFinancialFulfillment = false;

/**
 * @member {module:model/OnlinePayment} onlinePayment
 */
DocumentSettings.prototype.onlinePayment = undefined;

/**
 * @member {module:model/Round} round
 */
DocumentSettings.prototype.round = undefined;

/**
 * @member {Boolean} noSendOnlineszamlaByUser
 */
DocumentSettings.prototype.noSendOnlineszamlaByUser = undefined;

/**
 * @member {String} orderNumber
 */
DocumentSettings.prototype.orderNumber = undefined;

/**
 * @member {Number} placeId
 */
DocumentSettings.prototype.placeId = undefined;

/**
 * @member {Boolean} instantPayment
 */
DocumentSettings.prototype.instantPayment = undefined;

/**
 * @member {module:model/DocumentType} selectedType
 */
DocumentSettings.prototype.selectedType = undefined;

