/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DocumentBankAccount model module.
 * @module model/DocumentBankAccount
 * @version 3.0.14
 */
export class DocumentBankAccount {
  /**
   * Constructs a new <code>DocumentBankAccount</code>.
   * @alias module:model/DocumentBankAccount
   * @class
   * @param name {String} 
   * @param accountNumber {String} 
   */
  constructor(name, accountNumber) {
    this.name = name;
    this.accountNumber = accountNumber;
  }

  /**
   * Constructs a <code>DocumentBankAccount</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentBankAccount} obj Optional instance to populate.
   * @return {module:model/DocumentBankAccount} The populated <code>DocumentBankAccount</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentBankAccount();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('account_number'))
        obj.accountNumber = ApiClient.convertToType(data['account_number'], 'String');
      if (data.hasOwnProperty('account_number_iban'))
        obj.accountNumberIban = ApiClient.convertToType(data['account_number_iban'], 'String');
      if (data.hasOwnProperty('swift'))
        obj.swift = ApiClient.convertToType(data['swift'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
DocumentBankAccount.prototype.id = undefined;

/**
 * @member {String} name
 */
DocumentBankAccount.prototype.name = undefined;

/**
 * @member {String} accountNumber
 */
DocumentBankAccount.prototype.accountNumber = undefined;

/**
 * @member {String} accountNumberIban
 */
DocumentBankAccount.prototype.accountNumberIban = undefined;

/**
 * @member {String} swift
 */
DocumentBankAccount.prototype.swift = undefined;

