/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DocumentAncestor model module.
 * @module model/DocumentAncestor
 * @version 3.0.14
 */
export class DocumentAncestor {
  /**
   * Constructs a new <code>DocumentAncestor</code>.
   * An object representing related documents to another document.
   * @alias module:model/DocumentAncestor
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentAncestor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentAncestor} obj Optional instance to populate.
   * @return {module:model/DocumentAncestor} The populated <code>DocumentAncestor</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentAncestor();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('invoice_number'))
        obj.invoiceNumber = ApiClient.convertToType(data['invoice_number'], 'String');
    }
    return obj;
  }
}

/**
 * Unique identifier of the related document.
 * @member {Number} id
 */
DocumentAncestor.prototype.id = undefined;

/**
 * Invoice number of the related document.
 * @member {String} invoiceNumber
 */
DocumentAncestor.prototype.invoiceNumber = undefined;

