/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DocumentVatRateSummary} from './DocumentVatRateSummary';

/**
 * The DocumentSummary model module.
 * @module model/DocumentSummary
 * @version 3.0.14
 */
export class DocumentSummary {
  /**
   * Constructs a new <code>DocumentSummary</code>.
   * @alias module:model/DocumentSummary
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentSummary} obj Optional instance to populate.
   * @return {module:model/DocumentSummary} The populated <code>DocumentSummary</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentSummary();
      if (data.hasOwnProperty('net_amount'))
        obj.netAmount = ApiClient.convertToType(data['net_amount'], 'Number');
      if (data.hasOwnProperty('net_amount_local'))
        obj.netAmountLocal = ApiClient.convertToType(data['net_amount_local'], 'Number');
      if (data.hasOwnProperty('gross_amount_local'))
        obj.grossAmountLocal = ApiClient.convertToType(data['gross_amount_local'], 'Number');
      if (data.hasOwnProperty('vat_amount'))
        obj.vatAmount = ApiClient.convertToType(data['vat_amount'], 'Number');
      if (data.hasOwnProperty('vat_amount_local'))
        obj.vatAmountLocal = ApiClient.convertToType(data['vat_amount_local'], 'Number');
      if (data.hasOwnProperty('vat_rate_summary'))
        obj.vatRateSummary = ApiClient.convertToType(data['vat_rate_summary'], [DocumentVatRateSummary]);
    }
    return obj;
  }
}

/**
 * @member {Number} netAmount
 */
DocumentSummary.prototype.netAmount = undefined;

/**
 * @member {Number} netAmountLocal
 */
DocumentSummary.prototype.netAmountLocal = undefined;

/**
 * @member {Number} grossAmountLocal
 */
DocumentSummary.prototype.grossAmountLocal = undefined;

/**
 * @member {Number} vatAmount
 */
DocumentSummary.prototype.vatAmount = undefined;

/**
 * @member {Number} vatAmountLocal
 */
DocumentSummary.prototype.vatAmountLocal = undefined;

/**
 * @member {Array.<module:model/DocumentVatRateSummary>} vatRateSummary
 */
DocumentSummary.prototype.vatRateSummary = undefined;

