/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class Feature.
 * @enum {String}
 * @readonly
 */
const Feature = {
  /**
   * value: "api_limit_basic"
   * @const
   */
  apiLimitBasic: "api_limit_basic",

  /**
   * value: "api_limit_pro"
   * @const
   */
  apiLimitPro: "api_limit_pro",

  /**
   * value: "api_limit_standard"
   * @const
   */
  apiLimitStandard: "api_limit_standard",

  /**
   * value: "banksync_plus"
   * @const
   */
  banksyncPlus: "banksync_plus",

  /**
   * value: "campaign_manager_basic"
   * @const
   */
  campaignManagerBasic: "campaign_manager_basic",

  /**
   * value: "campaign_manager_standard"
   * @const
   */
  campaignManagerStandard: "campaign_manager_standard",

  /**
   * value: "ceginfo_enterprise"
   * @const
   */
  ceginfoEnterprise: "ceginfo_enterprise",

  /**
   * value: "ceginfo_pro"
   * @const
   */
  ceginfoPro: "ceginfo_pro",

  /**
   * value: "ceginfo_standard"
   * @const
   */
  ceginfoStandard: "ceginfo_standard",

  /**
   * value: "innovator"
   * @const
   */
  innovator: "innovator",

  /**
   * value: "limit_increase"
   * @const
   */
  limitIncrease: "limit_increase",

  /**
   * value: "master"
   * @const
   */
  master: "master",

  /**
   * value: "partnermonitor_basic"
   * @const
   */
  partnermonitorBasic: "partnermonitor_basic",

  /**
   * value: "partnermonitor_pro"
   * @const
   */
  partnermonitorPro: "partnermonitor_pro",

  /**
   * value: "partnermonitor_standard"
   * @const
   */
  partnermonitorStandard: "partnermonitor_standard",

  /**
   * value: "softpos"
   * @const
   */
  softpos: "softpos",

  /**
   * value: "subscription_basic"
   * @const
   */
  subscriptionBasic: "subscription_basic",

  /**
   * value: "subscription_pro"
   * @const
   */
  subscriptionPro: "subscription_pro",

  /**
   * value: "subscription_standard"
   * @const
   */
  subscriptionStandard: "subscription_standard",

  /**
   * value: "tendermonitor_standard"
   * @const
   */
  tendermonitorStandard: "tendermonitor_standard",

  /**
   * value: "tendermonitor_vip"
   * @const
   */
  tendermonitorVip: "tendermonitor_vip",

  /**
   * value: "whitelabel"
   * @const
   */
  whitelabel: "whitelabel",

  /**
   * Returns a <code>Feature</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/Feature} The enum <code>Feature</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {Feature};