/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Id model module.
 * @module model/Id
 * @version 3.0.14
 */
export class Id {
  /**
   * Constructs a new <code>Id</code>.
   * @alias module:model/Id
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Id</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Id} obj Optional instance to populate.
   * @return {module:model/Id} The populated <code>Id</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Id();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('legacy_id'))
        obj.legacyId = ApiClient.convertToType(data['legacy_id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Id.prototype.id = undefined;

/**
 * @member {Number} legacyId
 */
Id.prototype.legacyId = undefined;

