/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LedgerNumberInformation model module.
 * @module model/LedgerNumberInformation
 * @version 3.0.14
 */
export class LedgerNumberInformation {
  /**
   * Constructs a new <code>LedgerNumberInformation</code>.
   * @alias module:model/LedgerNumberInformation
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LedgerNumberInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LedgerNumberInformation} obj Optional instance to populate.
   * @return {module:model/LedgerNumberInformation} The populated <code>LedgerNumberInformation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LedgerNumberInformation();
      if (data.hasOwnProperty('bevetel'))
        obj.bevetel = ApiClient.convertToType(data['bevetel'], 'String');
      if (data.hasOwnProperty('vevo'))
        obj.vevo = ApiClient.convertToType(data['vevo'], 'String');
      if (data.hasOwnProperty('penztar'))
        obj.penztar = ApiClient.convertToType(data['penztar'], 'String');
      if (data.hasOwnProperty('afa'))
        obj.afa = ApiClient.convertToType(data['afa'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} bevetel
 */
LedgerNumberInformation.prototype.bevetel = undefined;

/**
 * @member {String} vevo
 */
LedgerNumberInformation.prototype.vevo = undefined;

/**
 * @member {String} penztar
 */
LedgerNumberInformation.prototype.penztar = undefined;

/**
 * @member {String} afa
 */
LedgerNumberInformation.prototype.afa = undefined;

