/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PaymentMethod} from './PaymentMethod';

/**
 * The ModificationDocumentInsert model module.
 * @module model/ModificationDocumentInsert
 * @version 3.0.14
 */
export class ModificationDocumentInsert {
  /**
   * Constructs a new <code>ModificationDocumentInsert</code>.
   * @alias module:model/ModificationDocumentInsert
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModificationDocumentInsert</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModificationDocumentInsert} obj Optional instance to populate.
   * @return {module:model/ModificationDocumentInsert} The populated <code>ModificationDocumentInsert</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModificationDocumentInsert();
      if (data.hasOwnProperty('due_date'))
        obj.dueDate = ApiClient.convertToType(data['due_date'], 'Date');
      if (data.hasOwnProperty('comment'))
        obj.comment = ApiClient.convertToType(data['comment'], 'String');
      if (data.hasOwnProperty('payment_method'))
        obj.paymentMethod = PaymentMethod.constructFromObject(data['payment_method']);
      if (data.hasOwnProperty('without_financial_fulfillment'))
        obj.withoutFinancialFulfillment = ApiClient.convertToType(data['without_financial_fulfillment'], 'Boolean');
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [OneOfModificationDocumentInsertItemsItems]);
    }
    return obj;
  }
}

/**
 * @member {Date} dueDate
 */
ModificationDocumentInsert.prototype.dueDate = undefined;

/**
 * @member {String} comment
 */
ModificationDocumentInsert.prototype.comment = undefined;

/**
 * @member {module:model/PaymentMethod} paymentMethod
 */
ModificationDocumentInsert.prototype.paymentMethod = undefined;

/**
 * @member {Boolean} withoutFinancialFulfillment
 * @default false
 */
ModificationDocumentInsert.prototype.withoutFinancialFulfillment = false;

/**
 * @member {Array.<Object>} items
 */
ModificationDocumentInsert.prototype.items = undefined;

