/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PaymentMethod} from './PaymentMethod';

/**
 * The PaymentHistory model module.
 * @module model/PaymentHistory
 * @version 3.0.14
 */
export class PaymentHistory {
  /**
   * Constructs a new <code>PaymentHistory</code>.
   * @alias module:model/PaymentHistory
   * @class
   * @param _date {Date} 
   * @param price {Number} 
   * @param paymentMethod {module:model/PaymentMethod} 
   */
  constructor(_date, price, paymentMethod) {
    this._date = _date;
    this.price = price;
    this.paymentMethod = paymentMethod;
  }

  /**
   * Constructs a <code>PaymentHistory</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentHistory} obj Optional instance to populate.
   * @return {module:model/PaymentHistory} The populated <code>PaymentHistory</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PaymentHistory();
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('payment_method'))
        obj.paymentMethod = PaymentMethod.constructFromObject(data['payment_method']);
      if (data.hasOwnProperty('voucher_number'))
        obj.voucherNumber = ApiClient.convertToType(data['voucher_number'], 'String');
      if (data.hasOwnProperty('conversion_rate'))
        obj.conversionRate = ApiClient.convertToType(data['conversion_rate'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Date} _date
 */
PaymentHistory.prototype._date = undefined;

/**
 * @member {Number} price
 */
PaymentHistory.prototype.price = undefined;

/**
 * @member {module:model/PaymentMethod} paymentMethod
 */
PaymentHistory.prototype.paymentMethod = undefined;

/**
 * @member {String} voucherNumber
 */
PaymentHistory.prototype.voucherNumber = undefined;

/**
 * @member {Number} conversionRate
 */
PaymentHistory.prototype.conversionRate = undefined;

