/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Product} from './Product';

/**
 * The ProductList model module.
 * @module model/ProductList
 * @version 3.0.14
 */
export class ProductList {
  /**
   * Constructs a new <code>ProductList</code>.
   * A object with a data property that contains an array of up to limit products. Each entry in the array is a separate product object. If no more products are available, the resulting array will be empty.
   * @alias module:model/ProductList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProductList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductList} obj Optional instance to populate.
   * @return {module:model/ProductList} The populated <code>ProductList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductList();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [Product]);
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
      if (data.hasOwnProperty('per_page'))
        obj.perPage = ApiClient.convertToType(data['per_page'], 'Number');
      if (data.hasOwnProperty('current_page'))
        obj.currentPage = ApiClient.convertToType(data['current_page'], 'Number');
      if (data.hasOwnProperty('last_page'))
        obj.lastPage = ApiClient.convertToType(data['last_page'], 'Number');
      if (data.hasOwnProperty('prev_page_url'))
        obj.prevPageUrl = ApiClient.convertToType(data['prev_page_url'], 'String');
      if (data.hasOwnProperty('next_page_url'))
        obj.nextPageUrl = ApiClient.convertToType(data['next_page_url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Product>} data
 */
ProductList.prototype.data = undefined;

/**
 * @member {Number} total
 */
ProductList.prototype.total = undefined;

/**
 * @member {Number} perPage
 */
ProductList.prototype.perPage = undefined;

/**
 * @member {Number} currentPage
 */
ProductList.prototype.currentPage = undefined;

/**
 * @member {Number} lastPage
 */
ProductList.prototype.lastPage = undefined;

/**
 * @member {String} prevPageUrl
 */
ProductList.prototype.prevPageUrl = undefined;

/**
 * @member {String} nextPageUrl
 */
ProductList.prototype.nextPageUrl = undefined;

