/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ReceiptItemData model module.
 * @module model/ReceiptItemData
 * @version 3.0.14
 */
export class ReceiptItemData {
  /**
   * Constructs a new <code>ReceiptItemData</code>.
   * @alias module:model/ReceiptItemData
   * @class
   * @param productId {Number} 
   */
  constructor(productId) {
    this.productId = productId;
  }

  /**
   * Constructs a <code>ReceiptItemData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReceiptItemData} obj Optional instance to populate.
   * @return {module:model/ReceiptItemData} The populated <code>ReceiptItemData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReceiptItemData();
      if (data.hasOwnProperty('product_id'))
        obj.productId = ApiClient.convertToType(data['product_id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} productId
 */
ReceiptItemData.prototype.productId = undefined;

// Implement OneOfReceiptInsertItemsItems interface:
