/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ServerTime model module.
 * @module model/ServerTime
 * @version 3.0.14
 */
export class ServerTime {
  /**
   * Constructs a new <code>ServerTime</code>.
   * @alias module:model/ServerTime
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ServerTime</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServerTime} obj Optional instance to populate.
   * @return {module:model/ServerTime} The populated <code>ServerTime</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServerTime();
      if (data.hasOwnProperty('epoch'))
        obj.epoch = ApiClient.convertToType(data['epoch'], 'Number');
      if (data.hasOwnProperty('formatted'))
        obj.formatted = ApiClient.convertToType(data['formatted'], 'String');
      if (data.hasOwnProperty('w3c'))
        obj.w3c = ApiClient.convertToType(data['w3c'], 'String');
      if (data.hasOwnProperty('timezone'))
        obj.timezone = ApiClient.convertToType(data['timezone'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} epoch
 */
ServerTime.prototype.epoch = undefined;

/**
 * @member {String} formatted
 */
ServerTime.prototype.formatted = undefined;

/**
 * @member {String} w3c
 */
ServerTime.prototype.w3c = undefined;

/**
 * @member {String} timezone
 */
ServerTime.prototype.timezone = undefined;

