/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {ClientErrorResponse} from '../model/ClientErrorResponse';
import {Id} from '../model/Id';
import {ServerErrorResponse} from '../model/ServerErrorResponse';
import {ServerTime} from '../model/ServerTime';
import {SubscriptionErrorResponse} from '../model/SubscriptionErrorResponse';
import {TaxNumber} from '../model/TaxNumber';
import {TooManyRequestsResponse} from '../model/TooManyRequestsResponse';
import {ValidationErrorResponse} from '../model/ValidationErrorResponse';

/**
* Util service.
* @module api/UtilApi
* @version 3.0.14
*/
export class UtilApi {

    /**
    * Constructs a new UtilApi. 
    * @alias module:api/UtilApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the checkTaxNumber operation.
     * @callback moduleapi/UtilApi~checkTaxNumberCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TaxNumber{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check tax number.
     * Check the given tax number format, and NAV validate.
     * @param {String} taxNumber 
     * @param {module:api/UtilApi~checkTaxNumberCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    checkTaxNumber(taxNumber, callback) {
      
      let postBody = null;
      // verify the required parameter 'taxNumber' is set
      if (taxNumber === undefined || taxNumber === null) {
        throw new Error("Missing the required parameter 'taxNumber' when calling checkTaxNumber");
      }

      let pathParams = {
        'tax_number': taxNumber
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxNumber;

      return this.apiClient.callApi(
        '/utils/check-tax-number/{tax_number}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getId operation.
     * @callback moduleapi/UtilApi~getIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Id{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Convert legacy ID to v3 ID.
     * Retrieves the API v3 ID.
     * @param {Number} id 
     * @param {module:api/UtilApi~getIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getId(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getId");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Id;

      return this.apiClient.callApi(
        '/utils/convert-legacy-id/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getServerTime operation.
     * @callback moduleapi/UtilApi~getServerTimeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ServerTime{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the server time
     * Return the server time.
     * @param {module:api/UtilApi~getServerTimeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getServerTime(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ServerTime;

      return this.apiClient.callApi(
        '/utils/time', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}