/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillingoApiV3);
  }
}(this, function(expect, BillingoApiV3) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Country', function() {
      beforeEach(function() {
        instance = BillingoApiV3.Country;
      });

      it('should create an instance of Country', function() {
        // TODO: update the code to test Country
        expect(instance).to.be.a('object');
      });

      it('should have the property empty', function() {
        expect(instance).to.have.property('empty');
        expect(instance.empty).to.be("");
      });

      it('should have the property AC', function() {
        expect(instance).to.have.property('AC');
        expect(instance.AC).to.be("AC");
      });

      it('should have the property AD', function() {
        expect(instance).to.have.property('AD');
        expect(instance.AD).to.be("AD");
      });

      it('should have the property AE', function() {
        expect(instance).to.have.property('AE');
        expect(instance.AE).to.be("AE");
      });

      it('should have the property AF', function() {
        expect(instance).to.have.property('AF');
        expect(instance.AF).to.be("AF");
      });

      it('should have the property AG', function() {
        expect(instance).to.have.property('AG');
        expect(instance.AG).to.be("AG");
      });

      it('should have the property AI', function() {
        expect(instance).to.have.property('AI');
        expect(instance.AI).to.be("AI");
      });

      it('should have the property AL', function() {
        expect(instance).to.have.property('AL');
        expect(instance.AL).to.be("AL");
      });

      it('should have the property AM', function() {
        expect(instance).to.have.property('AM');
        expect(instance.AM).to.be("AM");
      });

      it('should have the property AO', function() {
        expect(instance).to.have.property('AO');
        expect(instance.AO).to.be("AO");
      });

      it('should have the property AQ', function() {
        expect(instance).to.have.property('AQ');
        expect(instance.AQ).to.be("AQ");
      });

      it('should have the property AR', function() {
        expect(instance).to.have.property('AR');
        expect(instance.AR).to.be("AR");
      });

      it('should have the property AS', function() {
        expect(instance).to.have.property('AS');
        expect(instance.AS).to.be("AS");
      });

      it('should have the property AT', function() {
        expect(instance).to.have.property('AT');
        expect(instance.AT).to.be("AT");
      });

      it('should have the property AU', function() {
        expect(instance).to.have.property('AU');
        expect(instance.AU).to.be("AU");
      });

      it('should have the property AW', function() {
        expect(instance).to.have.property('AW');
        expect(instance.AW).to.be("AW");
      });

      it('should have the property AX', function() {
        expect(instance).to.have.property('AX');
        expect(instance.AX).to.be("AX");
      });

      it('should have the property AZ', function() {
        expect(instance).to.have.property('AZ');
        expect(instance.AZ).to.be("AZ");
      });

      it('should have the property BA', function() {
        expect(instance).to.have.property('BA');
        expect(instance.BA).to.be("BA");
      });

      it('should have the property BB', function() {
        expect(instance).to.have.property('BB');
        expect(instance.BB).to.be("BB");
      });

      it('should have the property BD', function() {
        expect(instance).to.have.property('BD');
        expect(instance.BD).to.be("BD");
      });

      it('should have the property BE', function() {
        expect(instance).to.have.property('BE');
        expect(instance.BE).to.be("BE");
      });

      it('should have the property BF', function() {
        expect(instance).to.have.property('BF');
        expect(instance.BF).to.be("BF");
      });

      it('should have the property BG', function() {
        expect(instance).to.have.property('BG');
        expect(instance.BG).to.be("BG");
      });

      it('should have the property BH', function() {
        expect(instance).to.have.property('BH');
        expect(instance.BH).to.be("BH");
      });

      it('should have the property BI', function() {
        expect(instance).to.have.property('BI');
        expect(instance.BI).to.be("BI");
      });

      it('should have the property BJ', function() {
        expect(instance).to.have.property('BJ');
        expect(instance.BJ).to.be("BJ");
      });

      it('should have the property BL', function() {
        expect(instance).to.have.property('BL');
        expect(instance.BL).to.be("BL");
      });

      it('should have the property BM', function() {
        expect(instance).to.have.property('BM');
        expect(instance.BM).to.be("BM");
      });

      it('should have the property BN', function() {
        expect(instance).to.have.property('BN');
        expect(instance.BN).to.be("BN");
      });

      it('should have the property BO', function() {
        expect(instance).to.have.property('BO');
        expect(instance.BO).to.be("BO");
      });

      it('should have the property BQ', function() {
        expect(instance).to.have.property('BQ');
        expect(instance.BQ).to.be("BQ");
      });

      it('should have the property BR', function() {
        expect(instance).to.have.property('BR');
        expect(instance.BR).to.be("BR");
      });

      it('should have the property BS', function() {
        expect(instance).to.have.property('BS');
        expect(instance.BS).to.be("BS");
      });

      it('should have the property BT', function() {
        expect(instance).to.have.property('BT');
        expect(instance.BT).to.be("BT");
      });

      it('should have the property BW', function() {
        expect(instance).to.have.property('BW');
        expect(instance.BW).to.be("BW");
      });

      it('should have the property BY', function() {
        expect(instance).to.have.property('BY');
        expect(instance.BY).to.be("BY");
      });

      it('should have the property BZ', function() {
        expect(instance).to.have.property('BZ');
        expect(instance.BZ).to.be("BZ");
      });

      it('should have the property CA', function() {
        expect(instance).to.have.property('CA');
        expect(instance.CA).to.be("CA");
      });

      it('should have the property CC', function() {
        expect(instance).to.have.property('CC');
        expect(instance.CC).to.be("CC");
      });

      it('should have the property CD', function() {
        expect(instance).to.have.property('CD');
        expect(instance.CD).to.be("CD");
      });

      it('should have the property CF', function() {
        expect(instance).to.have.property('CF');
        expect(instance.CF).to.be("CF");
      });

      it('should have the property CG', function() {
        expect(instance).to.have.property('CG');
        expect(instance.CG).to.be("CG");
      });

      it('should have the property CH', function() {
        expect(instance).to.have.property('CH');
        expect(instance.CH).to.be("CH");
      });

      it('should have the property CI', function() {
        expect(instance).to.have.property('CI');
        expect(instance.CI).to.be("CI");
      });

      it('should have the property CK', function() {
        expect(instance).to.have.property('CK');
        expect(instance.CK).to.be("CK");
      });

      it('should have the property CL', function() {
        expect(instance).to.have.property('CL');
        expect(instance.CL).to.be("CL");
      });

      it('should have the property CM', function() {
        expect(instance).to.have.property('CM');
        expect(instance.CM).to.be("CM");
      });

      it('should have the property CN', function() {
        expect(instance).to.have.property('CN');
        expect(instance.CN).to.be("CN");
      });

      it('should have the property CO', function() {
        expect(instance).to.have.property('CO');
        expect(instance.CO).to.be("CO");
      });

      it('should have the property CR', function() {
        expect(instance).to.have.property('CR');
        expect(instance.CR).to.be("CR");
      });

      it('should have the property CU', function() {
        expect(instance).to.have.property('CU');
        expect(instance.CU).to.be("CU");
      });

      it('should have the property CV', function() {
        expect(instance).to.have.property('CV');
        expect(instance.CV).to.be("CV");
      });

      it('should have the property CW', function() {
        expect(instance).to.have.property('CW');
        expect(instance.CW).to.be("CW");
      });

      it('should have the property CX', function() {
        expect(instance).to.have.property('CX');
        expect(instance.CX).to.be("CX");
      });

      it('should have the property CY', function() {
        expect(instance).to.have.property('CY');
        expect(instance.CY).to.be("CY");
      });

      it('should have the property CZ', function() {
        expect(instance).to.have.property('CZ');
        expect(instance.CZ).to.be("CZ");
      });

      it('should have the property DE', function() {
        expect(instance).to.have.property('DE');
        expect(instance.DE).to.be("DE");
      });

      it('should have the property DG', function() {
        expect(instance).to.have.property('DG');
        expect(instance.DG).to.be("DG");
      });

      it('should have the property DJ', function() {
        expect(instance).to.have.property('DJ');
        expect(instance.DJ).to.be("DJ");
      });

      it('should have the property DK', function() {
        expect(instance).to.have.property('DK');
        expect(instance.DK).to.be("DK");
      });

      it('should have the property DM', function() {
        expect(instance).to.have.property('DM');
        expect(instance.DM).to.be("DM");
      });

      it('should have the property DO', function() {
        expect(instance).to.have.property('DO');
        expect(instance.DO).to.be("DO");
      });

      it('should have the property DZ', function() {
        expect(instance).to.have.property('DZ');
        expect(instance.DZ).to.be("DZ");
      });

      it('should have the property EA', function() {
        expect(instance).to.have.property('EA');
        expect(instance.EA).to.be("EA");
      });

      it('should have the property EC', function() {
        expect(instance).to.have.property('EC');
        expect(instance.EC).to.be("EC");
      });

      it('should have the property EE', function() {
        expect(instance).to.have.property('EE');
        expect(instance.EE).to.be("EE");
      });

      it('should have the property EG', function() {
        expect(instance).to.have.property('EG');
        expect(instance.EG).to.be("EG");
      });

      it('should have the property EH', function() {
        expect(instance).to.have.property('EH');
        expect(instance.EH).to.be("EH");
      });

      it('should have the property ER', function() {
        expect(instance).to.have.property('ER');
        expect(instance.ER).to.be("ER");
      });

      it('should have the property ES', function() {
        expect(instance).to.have.property('ES');
        expect(instance.ES).to.be("ES");
      });

      it('should have the property ET', function() {
        expect(instance).to.have.property('ET');
        expect(instance.ET).to.be("ET");
      });

      it('should have the property FI', function() {
        expect(instance).to.have.property('FI');
        expect(instance.FI).to.be("FI");
      });

      it('should have the property FJ', function() {
        expect(instance).to.have.property('FJ');
        expect(instance.FJ).to.be("FJ");
      });

      it('should have the property FK', function() {
        expect(instance).to.have.property('FK');
        expect(instance.FK).to.be("FK");
      });

      it('should have the property FM', function() {
        expect(instance).to.have.property('FM');
        expect(instance.FM).to.be("FM");
      });

      it('should have the property FO', function() {
        expect(instance).to.have.property('FO');
        expect(instance.FO).to.be("FO");
      });

      it('should have the property FR', function() {
        expect(instance).to.have.property('FR');
        expect(instance.FR).to.be("FR");
      });

      it('should have the property GA', function() {
        expect(instance).to.have.property('GA');
        expect(instance.GA).to.be("GA");
      });

      it('should have the property GB', function() {
        expect(instance).to.have.property('GB');
        expect(instance.GB).to.be("GB");
      });

      it('should have the property GD', function() {
        expect(instance).to.have.property('GD');
        expect(instance.GD).to.be("GD");
      });

      it('should have the property GE', function() {
        expect(instance).to.have.property('GE');
        expect(instance.GE).to.be("GE");
      });

      it('should have the property GF', function() {
        expect(instance).to.have.property('GF');
        expect(instance.GF).to.be("GF");
      });

      it('should have the property GG', function() {
        expect(instance).to.have.property('GG');
        expect(instance.GG).to.be("GG");
      });

      it('should have the property GH', function() {
        expect(instance).to.have.property('GH');
        expect(instance.GH).to.be("GH");
      });

      it('should have the property GI', function() {
        expect(instance).to.have.property('GI');
        expect(instance.GI).to.be("GI");
      });

      it('should have the property GL', function() {
        expect(instance).to.have.property('GL');
        expect(instance.GL).to.be("GL");
      });

      it('should have the property GM', function() {
        expect(instance).to.have.property('GM');
        expect(instance.GM).to.be("GM");
      });

      it('should have the property GN', function() {
        expect(instance).to.have.property('GN');
        expect(instance.GN).to.be("GN");
      });

      it('should have the property GP', function() {
        expect(instance).to.have.property('GP');
        expect(instance.GP).to.be("GP");
      });

      it('should have the property GQ', function() {
        expect(instance).to.have.property('GQ');
        expect(instance.GQ).to.be("GQ");
      });

      it('should have the property GR', function() {
        expect(instance).to.have.property('GR');
        expect(instance.GR).to.be("GR");
      });

      it('should have the property GS', function() {
        expect(instance).to.have.property('GS');
        expect(instance.GS).to.be("GS");
      });

      it('should have the property GT', function() {
        expect(instance).to.have.property('GT');
        expect(instance.GT).to.be("GT");
      });

      it('should have the property GU', function() {
        expect(instance).to.have.property('GU');
        expect(instance.GU).to.be("GU");
      });

      it('should have the property GW', function() {
        expect(instance).to.have.property('GW');
        expect(instance.GW).to.be("GW");
      });

      it('should have the property GY', function() {
        expect(instance).to.have.property('GY');
        expect(instance.GY).to.be("GY");
      });

      it('should have the property HK', function() {
        expect(instance).to.have.property('HK');
        expect(instance.HK).to.be("HK");
      });

      it('should have the property HN', function() {
        expect(instance).to.have.property('HN');
        expect(instance.HN).to.be("HN");
      });

      it('should have the property HR', function() {
        expect(instance).to.have.property('HR');
        expect(instance.HR).to.be("HR");
      });

      it('should have the property HT', function() {
        expect(instance).to.have.property('HT');
        expect(instance.HT).to.be("HT");
      });

      it('should have the property HU', function() {
        expect(instance).to.have.property('HU');
        expect(instance.HU).to.be("HU");
      });

      it('should have the property IC', function() {
        expect(instance).to.have.property('IC');
        expect(instance.IC).to.be("IC");
      });

      it('should have the property ID', function() {
        expect(instance).to.have.property('ID');
        expect(instance.ID).to.be("ID");
      });

      it('should have the property IE', function() {
        expect(instance).to.have.property('IE');
        expect(instance.IE).to.be("IE");
      });

      it('should have the property IL', function() {
        expect(instance).to.have.property('IL');
        expect(instance.IL).to.be("IL");
      });

      it('should have the property IM', function() {
        expect(instance).to.have.property('IM');
        expect(instance.IM).to.be("IM");
      });

      it('should have the property IN', function() {
        expect(instance).to.have.property('IN');
        expect(instance.IN).to.be("IN");
      });

      it('should have the property IO', function() {
        expect(instance).to.have.property('IO');
        expect(instance.IO).to.be("IO");
      });

      it('should have the property IQ', function() {
        expect(instance).to.have.property('IQ');
        expect(instance.IQ).to.be("IQ");
      });

      it('should have the property IR', function() {
        expect(instance).to.have.property('IR');
        expect(instance.IR).to.be("IR");
      });

      it('should have the property IS', function() {
        expect(instance).to.have.property('IS');
        expect(instance.IS).to.be("IS");
      });

      it('should have the property IT', function() {
        expect(instance).to.have.property('IT');
        expect(instance.IT).to.be("IT");
      });

      it('should have the property JE', function() {
        expect(instance).to.have.property('JE');
        expect(instance.JE).to.be("JE");
      });

      it('should have the property JM', function() {
        expect(instance).to.have.property('JM');
        expect(instance.JM).to.be("JM");
      });

      it('should have the property JO', function() {
        expect(instance).to.have.property('JO');
        expect(instance.JO).to.be("JO");
      });

      it('should have the property JP', function() {
        expect(instance).to.have.property('JP');
        expect(instance.JP).to.be("JP");
      });

      it('should have the property KE', function() {
        expect(instance).to.have.property('KE');
        expect(instance.KE).to.be("KE");
      });

      it('should have the property KG', function() {
        expect(instance).to.have.property('KG');
        expect(instance.KG).to.be("KG");
      });

      it('should have the property KH', function() {
        expect(instance).to.have.property('KH');
        expect(instance.KH).to.be("KH");
      });

      it('should have the property KI', function() {
        expect(instance).to.have.property('KI');
        expect(instance.KI).to.be("KI");
      });

      it('should have the property KM', function() {
        expect(instance).to.have.property('KM');
        expect(instance.KM).to.be("KM");
      });

      it('should have the property KN', function() {
        expect(instance).to.have.property('KN');
        expect(instance.KN).to.be("KN");
      });

      it('should have the property KP', function() {
        expect(instance).to.have.property('KP');
        expect(instance.KP).to.be("KP");
      });

      it('should have the property KR', function() {
        expect(instance).to.have.property('KR');
        expect(instance.KR).to.be("KR");
      });

      it('should have the property KW', function() {
        expect(instance).to.have.property('KW');
        expect(instance.KW).to.be("KW");
      });

      it('should have the property KY', function() {
        expect(instance).to.have.property('KY');
        expect(instance.KY).to.be("KY");
      });

      it('should have the property KZ', function() {
        expect(instance).to.have.property('KZ');
        expect(instance.KZ).to.be("KZ");
      });

      it('should have the property LA', function() {
        expect(instance).to.have.property('LA');
        expect(instance.LA).to.be("LA");
      });

      it('should have the property LB', function() {
        expect(instance).to.have.property('LB');
        expect(instance.LB).to.be("LB");
      });

      it('should have the property LC', function() {
        expect(instance).to.have.property('LC');
        expect(instance.LC).to.be("LC");
      });

      it('should have the property LI', function() {
        expect(instance).to.have.property('LI');
        expect(instance.LI).to.be("LI");
      });

      it('should have the property LK', function() {
        expect(instance).to.have.property('LK');
        expect(instance.LK).to.be("LK");
      });

      it('should have the property LR', function() {
        expect(instance).to.have.property('LR');
        expect(instance.LR).to.be("LR");
      });

      it('should have the property LS', function() {
        expect(instance).to.have.property('LS');
        expect(instance.LS).to.be("LS");
      });

      it('should have the property LT', function() {
        expect(instance).to.have.property('LT');
        expect(instance.LT).to.be("LT");
      });

      it('should have the property LU', function() {
        expect(instance).to.have.property('LU');
        expect(instance.LU).to.be("LU");
      });

      it('should have the property LV', function() {
        expect(instance).to.have.property('LV');
        expect(instance.LV).to.be("LV");
      });

      it('should have the property LY', function() {
        expect(instance).to.have.property('LY');
        expect(instance.LY).to.be("LY");
      });

      it('should have the property MA', function() {
        expect(instance).to.have.property('MA');
        expect(instance.MA).to.be("MA");
      });

      it('should have the property MC', function() {
        expect(instance).to.have.property('MC');
        expect(instance.MC).to.be("MC");
      });

      it('should have the property MD', function() {
        expect(instance).to.have.property('MD');
        expect(instance.MD).to.be("MD");
      });

      it('should have the property ME', function() {
        expect(instance).to.have.property('ME');
        expect(instance.ME).to.be("ME");
      });

      it('should have the property MF', function() {
        expect(instance).to.have.property('MF');
        expect(instance.MF).to.be("MF");
      });

      it('should have the property MG', function() {
        expect(instance).to.have.property('MG');
        expect(instance.MG).to.be("MG");
      });

      it('should have the property MH', function() {
        expect(instance).to.have.property('MH');
        expect(instance.MH).to.be("MH");
      });

      it('should have the property MK', function() {
        expect(instance).to.have.property('MK');
        expect(instance.MK).to.be("MK");
      });

      it('should have the property ML', function() {
        expect(instance).to.have.property('ML');
        expect(instance.ML).to.be("ML");
      });

      it('should have the property MM', function() {
        expect(instance).to.have.property('MM');
        expect(instance.MM).to.be("MM");
      });

      it('should have the property MN', function() {
        expect(instance).to.have.property('MN');
        expect(instance.MN).to.be("MN");
      });

      it('should have the property MO', function() {
        expect(instance).to.have.property('MO');
        expect(instance.MO).to.be("MO");
      });

      it('should have the property MP', function() {
        expect(instance).to.have.property('MP');
        expect(instance.MP).to.be("MP");
      });

      it('should have the property MQ', function() {
        expect(instance).to.have.property('MQ');
        expect(instance.MQ).to.be("MQ");
      });

      it('should have the property MR', function() {
        expect(instance).to.have.property('MR');
        expect(instance.MR).to.be("MR");
      });

      it('should have the property MS', function() {
        expect(instance).to.have.property('MS');
        expect(instance.MS).to.be("MS");
      });

      it('should have the property MT', function() {
        expect(instance).to.have.property('MT');
        expect(instance.MT).to.be("MT");
      });

      it('should have the property MU', function() {
        expect(instance).to.have.property('MU');
        expect(instance.MU).to.be("MU");
      });

      it('should have the property MV', function() {
        expect(instance).to.have.property('MV');
        expect(instance.MV).to.be("MV");
      });

      it('should have the property MW', function() {
        expect(instance).to.have.property('MW');
        expect(instance.MW).to.be("MW");
      });

      it('should have the property MX', function() {
        expect(instance).to.have.property('MX');
        expect(instance.MX).to.be("MX");
      });

      it('should have the property MY', function() {
        expect(instance).to.have.property('MY');
        expect(instance.MY).to.be("MY");
      });

      it('should have the property MZ', function() {
        expect(instance).to.have.property('MZ');
        expect(instance.MZ).to.be("MZ");
      });

      it('should have the property NA', function() {
        expect(instance).to.have.property('NA');
        expect(instance.NA).to.be("NA");
      });

      it('should have the property NC', function() {
        expect(instance).to.have.property('NC');
        expect(instance.NC).to.be("NC");
      });

      it('should have the property NE', function() {
        expect(instance).to.have.property('NE');
        expect(instance.NE).to.be("NE");
      });

      it('should have the property NF', function() {
        expect(instance).to.have.property('NF');
        expect(instance.NF).to.be("NF");
      });

      it('should have the property NG', function() {
        expect(instance).to.have.property('NG');
        expect(instance.NG).to.be("NG");
      });

      it('should have the property NI', function() {
        expect(instance).to.have.property('NI');
        expect(instance.NI).to.be("NI");
      });

      it('should have the property NL', function() {
        expect(instance).to.have.property('NL');
        expect(instance.NL).to.be("NL");
      });

      it('should have the property NO', function() {
        expect(instance).to.have.property('NO');
        expect(instance.NO).to.be("NO");
      });

      it('should have the property NP', function() {
        expect(instance).to.have.property('NP');
        expect(instance.NP).to.be("NP");
      });

      it('should have the property NR', function() {
        expect(instance).to.have.property('NR');
        expect(instance.NR).to.be("NR");
      });

      it('should have the property NU', function() {
        expect(instance).to.have.property('NU');
        expect(instance.NU).to.be("NU");
      });

      it('should have the property NZ', function() {
        expect(instance).to.have.property('NZ');
        expect(instance.NZ).to.be("NZ");
      });

      it('should have the property OM', function() {
        expect(instance).to.have.property('OM');
        expect(instance.OM).to.be("OM");
      });

      it('should have the property PA', function() {
        expect(instance).to.have.property('PA');
        expect(instance.PA).to.be("PA");
      });

      it('should have the property PE', function() {
        expect(instance).to.have.property('PE');
        expect(instance.PE).to.be("PE");
      });

      it('should have the property PF', function() {
        expect(instance).to.have.property('PF');
        expect(instance.PF).to.be("PF");
      });

      it('should have the property PG', function() {
        expect(instance).to.have.property('PG');
        expect(instance.PG).to.be("PG");
      });

      it('should have the property PH', function() {
        expect(instance).to.have.property('PH');
        expect(instance.PH).to.be("PH");
      });

      it('should have the property PK', function() {
        expect(instance).to.have.property('PK');
        expect(instance.PK).to.be("PK");
      });

      it('should have the property PL', function() {
        expect(instance).to.have.property('PL');
        expect(instance.PL).to.be("PL");
      });

      it('should have the property PM', function() {
        expect(instance).to.have.property('PM');
        expect(instance.PM).to.be("PM");
      });

      it('should have the property PN', function() {
        expect(instance).to.have.property('PN');
        expect(instance.PN).to.be("PN");
      });

      it('should have the property PR', function() {
        expect(instance).to.have.property('PR');
        expect(instance.PR).to.be("PR");
      });

      it('should have the property PS', function() {
        expect(instance).to.have.property('PS');
        expect(instance.PS).to.be("PS");
      });

      it('should have the property PT', function() {
        expect(instance).to.have.property('PT');
        expect(instance.PT).to.be("PT");
      });

      it('should have the property PW', function() {
        expect(instance).to.have.property('PW');
        expect(instance.PW).to.be("PW");
      });

      it('should have the property PY', function() {
        expect(instance).to.have.property('PY');
        expect(instance.PY).to.be("PY");
      });

      it('should have the property QA', function() {
        expect(instance).to.have.property('QA');
        expect(instance.QA).to.be("QA");
      });

      it('should have the property RE', function() {
        expect(instance).to.have.property('RE');
        expect(instance.RE).to.be("RE");
      });

      it('should have the property RO', function() {
        expect(instance).to.have.property('RO');
        expect(instance.RO).to.be("RO");
      });

      it('should have the property RS', function() {
        expect(instance).to.have.property('RS');
        expect(instance.RS).to.be("RS");
      });

      it('should have the property RU', function() {
        expect(instance).to.have.property('RU');
        expect(instance.RU).to.be("RU");
      });

      it('should have the property RW', function() {
        expect(instance).to.have.property('RW');
        expect(instance.RW).to.be("RW");
      });

      it('should have the property SA', function() {
        expect(instance).to.have.property('SA');
        expect(instance.SA).to.be("SA");
      });

      it('should have the property SB', function() {
        expect(instance).to.have.property('SB');
        expect(instance.SB).to.be("SB");
      });

      it('should have the property SC', function() {
        expect(instance).to.have.property('SC');
        expect(instance.SC).to.be("SC");
      });

      it('should have the property SD', function() {
        expect(instance).to.have.property('SD');
        expect(instance.SD).to.be("SD");
      });

      it('should have the property SE', function() {
        expect(instance).to.have.property('SE');
        expect(instance.SE).to.be("SE");
      });

      it('should have the property SG', function() {
        expect(instance).to.have.property('SG');
        expect(instance.SG).to.be("SG");
      });

      it('should have the property SH', function() {
        expect(instance).to.have.property('SH');
        expect(instance.SH).to.be("SH");
      });

      it('should have the property SI', function() {
        expect(instance).to.have.property('SI');
        expect(instance.SI).to.be("SI");
      });

      it('should have the property SJ', function() {
        expect(instance).to.have.property('SJ');
        expect(instance.SJ).to.be("SJ");
      });

      it('should have the property SK', function() {
        expect(instance).to.have.property('SK');
        expect(instance.SK).to.be("SK");
      });

      it('should have the property SL', function() {
        expect(instance).to.have.property('SL');
        expect(instance.SL).to.be("SL");
      });

      it('should have the property SM', function() {
        expect(instance).to.have.property('SM');
        expect(instance.SM).to.be("SM");
      });

      it('should have the property SN', function() {
        expect(instance).to.have.property('SN');
        expect(instance.SN).to.be("SN");
      });

      it('should have the property SO', function() {
        expect(instance).to.have.property('SO');
        expect(instance.SO).to.be("SO");
      });

      it('should have the property SR', function() {
        expect(instance).to.have.property('SR');
        expect(instance.SR).to.be("SR");
      });

      it('should have the property SS', function() {
        expect(instance).to.have.property('SS');
        expect(instance.SS).to.be("SS");
      });

      it('should have the property ST', function() {
        expect(instance).to.have.property('ST');
        expect(instance.ST).to.be("ST");
      });

      it('should have the property SV', function() {
        expect(instance).to.have.property('SV');
        expect(instance.SV).to.be("SV");
      });

      it('should have the property SX', function() {
        expect(instance).to.have.property('SX');
        expect(instance.SX).to.be("SX");
      });

      it('should have the property SY', function() {
        expect(instance).to.have.property('SY');
        expect(instance.SY).to.be("SY");
      });

      it('should have the property SZ', function() {
        expect(instance).to.have.property('SZ');
        expect(instance.SZ).to.be("SZ");
      });

      it('should have the property TA', function() {
        expect(instance).to.have.property('TA');
        expect(instance.TA).to.be("TA");
      });

      it('should have the property TC', function() {
        expect(instance).to.have.property('TC');
        expect(instance.TC).to.be("TC");
      });

      it('should have the property TD', function() {
        expect(instance).to.have.property('TD');
        expect(instance.TD).to.be("TD");
      });

      it('should have the property TF', function() {
        expect(instance).to.have.property('TF');
        expect(instance.TF).to.be("TF");
      });

      it('should have the property TG', function() {
        expect(instance).to.have.property('TG');
        expect(instance.TG).to.be("TG");
      });

      it('should have the property TH', function() {
        expect(instance).to.have.property('TH');
        expect(instance.TH).to.be("TH");
      });

      it('should have the property TJ', function() {
        expect(instance).to.have.property('TJ');
        expect(instance.TJ).to.be("TJ");
      });

      it('should have the property TK', function() {
        expect(instance).to.have.property('TK');
        expect(instance.TK).to.be("TK");
      });

      it('should have the property TL', function() {
        expect(instance).to.have.property('TL');
        expect(instance.TL).to.be("TL");
      });

      it('should have the property TM', function() {
        expect(instance).to.have.property('TM');
        expect(instance.TM).to.be("TM");
      });

      it('should have the property TN', function() {
        expect(instance).to.have.property('TN');
        expect(instance.TN).to.be("TN");
      });

      it('should have the property TO', function() {
        expect(instance).to.have.property('TO');
        expect(instance.TO).to.be("TO");
      });

      it('should have the property TR', function() {
        expect(instance).to.have.property('TR');
        expect(instance.TR).to.be("TR");
      });

      it('should have the property TT', function() {
        expect(instance).to.have.property('TT');
        expect(instance.TT).to.be("TT");
      });

      it('should have the property TV', function() {
        expect(instance).to.have.property('TV');
        expect(instance.TV).to.be("TV");
      });

      it('should have the property TW', function() {
        expect(instance).to.have.property('TW');
        expect(instance.TW).to.be("TW");
      });

      it('should have the property TZ', function() {
        expect(instance).to.have.property('TZ');
        expect(instance.TZ).to.be("TZ");
      });

      it('should have the property UA', function() {
        expect(instance).to.have.property('UA');
        expect(instance.UA).to.be("UA");
      });

      it('should have the property UG', function() {
        expect(instance).to.have.property('UG');
        expect(instance.UG).to.be("UG");
      });

      it('should have the property UM', function() {
        expect(instance).to.have.property('UM');
        expect(instance.UM).to.be("UM");
      });

      it('should have the property US', function() {
        expect(instance).to.have.property('US');
        expect(instance.US).to.be("US");
      });

      it('should have the property UY', function() {
        expect(instance).to.have.property('UY');
        expect(instance.UY).to.be("UY");
      });

      it('should have the property UZ', function() {
        expect(instance).to.have.property('UZ');
        expect(instance.UZ).to.be("UZ");
      });

      it('should have the property VA', function() {
        expect(instance).to.have.property('VA');
        expect(instance.VA).to.be("VA");
      });

      it('should have the property VC', function() {
        expect(instance).to.have.property('VC');
        expect(instance.VC).to.be("VC");
      });

      it('should have the property VE', function() {
        expect(instance).to.have.property('VE');
        expect(instance.VE).to.be("VE");
      });

      it('should have the property VG', function() {
        expect(instance).to.have.property('VG');
        expect(instance.VG).to.be("VG");
      });

      it('should have the property VI', function() {
        expect(instance).to.have.property('VI');
        expect(instance.VI).to.be("VI");
      });

      it('should have the property VN', function() {
        expect(instance).to.have.property('VN');
        expect(instance.VN).to.be("VN");
      });

      it('should have the property VU', function() {
        expect(instance).to.have.property('VU');
        expect(instance.VU).to.be("VU");
      });

      it('should have the property WF', function() {
        expect(instance).to.have.property('WF');
        expect(instance.WF).to.be("WF");
      });

      it('should have the property WS', function() {
        expect(instance).to.have.property('WS');
        expect(instance.WS).to.be("WS");
      });

      it('should have the property XA', function() {
        expect(instance).to.have.property('XA');
        expect(instance.XA).to.be("XA");
      });

      it('should have the property XB', function() {
        expect(instance).to.have.property('XB');
        expect(instance.XB).to.be("XB");
      });

      it('should have the property XK', function() {
        expect(instance).to.have.property('XK');
        expect(instance.XK).to.be("XK");
      });

      it('should have the property YE', function() {
        expect(instance).to.have.property('YE');
        expect(instance.YE).to.be("YE");
      });

      it('should have the property YT', function() {
        expect(instance).to.have.property('YT');
        expect(instance.YT).to.be("YT");
      });

      it('should have the property ZA', function() {
        expect(instance).to.have.property('ZA');
        expect(instance.ZA).to.be("ZA");
      });

      it('should have the property ZM', function() {
        expect(instance).to.have.property('ZM');
        expect(instance.ZM).to.be("ZM");
      });

      it('should have the property ZW', function() {
        expect(instance).to.have.property('ZW');
        expect(instance.ZW).to.be("ZW");
      });

    });
  });

}));
