/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillingoApiV3);
  }
}(this, function(expect, BillingoApiV3) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DocumentLanguage', function() {
      beforeEach(function() {
        instance = BillingoApiV3.DocumentLanguage;
      });

      it('should create an instance of DocumentLanguage', function() {
        // TODO: update the code to test DocumentLanguage
        expect(instance).to.be.a('object');
      });

      it('should have the property de', function() {
        expect(instance).to.have.property('de');
        expect(instance.de).to.be("de");
      });

      it('should have the property en', function() {
        expect(instance).to.have.property('en');
        expect(instance.en).to.be("en");
      });

      it('should have the property fr', function() {
        expect(instance).to.have.property('fr');
        expect(instance.fr).to.be("fr");
      });

      it('should have the property hr', function() {
        expect(instance).to.have.property('hr');
        expect(instance.hr).to.be("hr");
      });

      it('should have the property hu', function() {
        expect(instance).to.have.property('hu');
        expect(instance.hu).to.be("hu");
      });

      it('should have the property it', function() {
        expect(instance).to.have.property('it');
        expect(instance.it).to.be("it");
      });

      it('should have the property ro', function() {
        expect(instance).to.have.property('ro');
        expect(instance.ro).to.be("ro");
      });

      it('should have the property sk', function() {
        expect(instance).to.have.property('sk');
        expect(instance.sk).to.be("sk");
      });

      it('should have the property us', function() {
        expect(instance).to.have.property('us');
        expect(instance.us).to.be("us");
      });

    });
  });

}));
