/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillingoApiV3);
  }
}(this, function(expect, BillingoApiV3) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DocumentExportStatusState', function() {
      beforeEach(function() {
        instance = BillingoApiV3.DocumentExportStatusState;
      });

      it('should create an instance of DocumentExportStatusState', function() {
        // TODO: update the code to test DocumentExportStatusState
        expect(instance).to.be.a('object');
      });

      it('should have the property fail', function() {
        expect(instance).to.have.property('fail');
        expect(instance.fail).to.be("fail");
      });

      it('should have the property pending', function() {
        expect(instance).to.have.property('pending');
        expect(instance.pending).to.be("pending");
      });

      it('should have the property processing', function() {
        expect(instance).to.have.property('processing');
        expect(instance.processing).to.be("processing");
      });

      it('should have the property success', function() {
        expect(instance).to.have.property('success');
        expect(instance.success).to.be("success");
      });

      it('should have the property warning', function() {
        expect(instance).to.have.property('warning');
        expect(instance.warning).to.be("warning");
      });

    });
  });

}));
