/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillingoApiV3);
  }
}(this, function(expect, BillingoApiV3) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DocumentSettings', function() {
      beforeEach(function() {
        instance = new BillingoApiV3.DocumentSettings();
      });

      it('should create an instance of DocumentSettings', function() {
        // TODO: update the code to test DocumentSettings
        expect(instance).to.be.a(BillingoApiV3.DocumentSettings);
      });

      it('should have the property mediatedService (base name: "mediated_service")', function() {
        // TODO: update the code to test the property mediatedService
        expect(instance).to.have.property('mediatedService');
        // expect(instance.mediatedService).to.be(expectedValueLiteral);
      });

      it('should have the property withoutFinancialFulfillment (base name: "without_financial_fulfillment")', function() {
        // TODO: update the code to test the property withoutFinancialFulfillment
        expect(instance).to.have.property('withoutFinancialFulfillment');
        // expect(instance.withoutFinancialFulfillment).to.be(expectedValueLiteral);
      });

      it('should have the property onlinePayment (base name: "online_payment")', function() {
        // TODO: update the code to test the property onlinePayment
        expect(instance).to.have.property('onlinePayment');
        // expect(instance.onlinePayment).to.be(expectedValueLiteral);
      });

      it('should have the property round (base name: "round")', function() {
        // TODO: update the code to test the property round
        expect(instance).to.have.property('round');
        // expect(instance.round).to.be(expectedValueLiteral);
      });

      it('should have the property noSendOnlineszamlaByUser (base name: "no_send_onlineszamla_by_user")', function() {
        // TODO: update the code to test the property noSendOnlineszamlaByUser
        expect(instance).to.have.property('noSendOnlineszamlaByUser');
        // expect(instance.noSendOnlineszamlaByUser).to.be(expectedValueLiteral);
      });

      it('should have the property orderNumber (base name: "order_number")', function() {
        // TODO: update the code to test the property orderNumber
        expect(instance).to.have.property('orderNumber');
        // expect(instance.orderNumber).to.be(expectedValueLiteral);
      });

      it('should have the property placeId (base name: "place_id")', function() {
        // TODO: update the code to test the property placeId
        expect(instance).to.have.property('placeId');
        // expect(instance.placeId).to.be(expectedValueLiteral);
      });

      it('should have the property instantPayment (base name: "instant_payment")', function() {
        // TODO: update the code to test the property instantPayment
        expect(instance).to.have.property('instantPayment');
        // expect(instance.instantPayment).to.be(expectedValueLiteral);
      });

      it('should have the property selectedType (base name: "selected_type")', function() {
        // TODO: update the code to test the property selectedType
        expect(instance).to.have.property('selectedType');
        // expect(instance.selectedType).to.be(expectedValueLiteral);
      });

    });
  });

}));
