/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillingoApiV3);
  }
}(this, function(expect, BillingoApiV3) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DocumentSummary', function() {
      beforeEach(function() {
        instance = new BillingoApiV3.DocumentSummary();
      });

      it('should create an instance of DocumentSummary', function() {
        // TODO: update the code to test DocumentSummary
        expect(instance).to.be.a(BillingoApiV3.DocumentSummary);
      });

      it('should have the property netAmount (base name: "net_amount")', function() {
        // TODO: update the code to test the property netAmount
        expect(instance).to.have.property('netAmount');
        // expect(instance.netAmount).to.be(expectedValueLiteral);
      });

      it('should have the property netAmountLocal (base name: "net_amount_local")', function() {
        // TODO: update the code to test the property netAmountLocal
        expect(instance).to.have.property('netAmountLocal');
        // expect(instance.netAmountLocal).to.be(expectedValueLiteral);
      });

      it('should have the property grossAmountLocal (base name: "gross_amount_local")', function() {
        // TODO: update the code to test the property grossAmountLocal
        expect(instance).to.have.property('grossAmountLocal');
        // expect(instance.grossAmountLocal).to.be(expectedValueLiteral);
      });

      it('should have the property vatAmount (base name: "vat_amount")', function() {
        // TODO: update the code to test the property vatAmount
        expect(instance).to.have.property('vatAmount');
        // expect(instance.vatAmount).to.be(expectedValueLiteral);
      });

      it('should have the property vatAmountLocal (base name: "vat_amount_local")', function() {
        // TODO: update the code to test the property vatAmountLocal
        expect(instance).to.have.property('vatAmountLocal');
        // expect(instance.vatAmountLocal).to.be(expectedValueLiteral);
      });

      it('should have the property vatRateSummary (base name: "vat_rate_summary")', function() {
        // TODO: update the code to test the property vatRateSummary
        expect(instance).to.have.property('vatRateSummary');
        // expect(instance.vatRateSummary).to.be(expectedValueLiteral);
      });

    });
  });

}));
