/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillingoApiV3);
  }
}(this, function(expect, BillingoApiV3) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DocumentVatRateSummary', function() {
      beforeEach(function() {
        instance = new BillingoApiV3.DocumentVatRateSummary();
      });

      it('should create an instance of DocumentVatRateSummary', function() {
        // TODO: update the code to test DocumentVatRateSummary
        expect(instance).to.be.a(BillingoApiV3.DocumentVatRateSummary);
      });

      it('should have the property vatName (base name: "vat_name")', function() {
        // TODO: update the code to test the property vatName
        expect(instance).to.have.property('vatName');
        // expect(instance.vatName).to.be(expectedValueLiteral);
      });

      it('should have the property vatPercentage (base name: "vat_percentage")', function() {
        // TODO: update the code to test the property vatPercentage
        expect(instance).to.have.property('vatPercentage');
        // expect(instance.vatPercentage).to.be(expectedValueLiteral);
      });

      it('should have the property vatRateNetAmount (base name: "vat_rate_net_amount")', function() {
        // TODO: update the code to test the property vatRateNetAmount
        expect(instance).to.have.property('vatRateNetAmount');
        // expect(instance.vatRateNetAmount).to.be(expectedValueLiteral);
      });

      it('should have the property vatRateVatAmount (base name: "vat_rate_vat_amount")', function() {
        // TODO: update the code to test the property vatRateVatAmount
        expect(instance).to.have.property('vatRateVatAmount');
        // expect(instance.vatRateVatAmount).to.be(expectedValueLiteral);
      });

      it('should have the property vatRateVatAmountLocal (base name: "vat_rate_vat_amount_local")', function() {
        // TODO: update the code to test the property vatRateVatAmountLocal
        expect(instance).to.have.property('vatRateVatAmountLocal');
        // expect(instance.vatRateVatAmountLocal).to.be(expectedValueLiteral);
      });

      it('should have the property vatRateGrossAmount (base name: "vat_rate_gross_amount")', function() {
        // TODO: update the code to test the property vatRateGrossAmount
        expect(instance).to.have.property('vatRateGrossAmount');
        // expect(instance.vatRateGrossAmount).to.be(expectedValueLiteral);
      });

    });
  });

}));
